### ISSUE TITLE
Can't see patterns without hash

### ISSUE THREAD

**Issue by dwaps** [LeaVerou/css3patterns#158]
The url https://leaverou.github.io/css3patterns doesn't show patterns...
It must delete display property on line 119:

![image](https://user-images.githubusercontent.com/9659087/79445978-cfdba600-7fdd-11ea-8430-3c737840476b.png)

**Comment by LeaVerou** [comment]
It shows them fine for me?

**Comment by dwaps** [comment]
Mmmm, it's strange... I test that from another browsers...

**Comment by dwaps** [comment]
Chrome Google Canary, ok.
Firefox Developper Edition, not ok.
Chrome, not ok.
Safari, ok.

I wonder if this is due to a (native ?) extension...

**Comment by dwaps** [comment]
Oh dear Lea !
Sorry, I found it: some extensions conflict with your code...
So...  it's not your fault ! 😃
I close that. Bye.

**Comment by LeaVerou** [comment]
Works fine for me in both stable Chrome and stable Firefox...

**Comment by dwaps** [comment]
Right, this is a conflict with extensions in various stables browsers.. up
